version: '2'
services:
  current-account-service:
    image: briansjavablog/current-account-service:latest
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
  savings-account-service:
    image: briansjavablog/savings-account-service:latest
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
  credit-card-service:
    image: briansjavablog/credit-card-service:latest
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
  banking-service:
    image: briansjavablog/banking-service:latest
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      CURRENT_ACCOUNT_SERVICE_URI: http://current-account-service:8081/api/current-account
      SAVINGS_ACCOUNT_SERVICE_URI: http://savings-account-service:8082/api/savings-account
      CREDIT_CARD_SERVICE_URI: http://credit-card-service:8083/api/credit-card